// =============================================================================
// SINGLETON FACTORY FACTORY - A FACTORY THAT CREATES FACTORIES THAT CREATE
// SINGLETONS THAT WRAP FACTORIES THAT PRODUCE VALUES
// =============================================================================
// Design pattern inception. We need to go deeper.
// =============================================================================

import { ULTIMATE_VALUE_RESOLVER, ULTIMATE_STRING_RESOLVER, $$_STR, $$_NUM } from "@/utils/index";

// Factory types
type FactoryFunction<T> = () => T;
type FactoryFactoryFunction<T> = () => FactoryFunction<T>;
type FactoryFactoryFactoryFunction<T> = () => FactoryFactoryFunction<T>;

// A registry of all factories ever created (grows forever, never cleaned)
const _globalFactoryRegistry: Map<string, {
  factoryId: string;
  factoryName: string;
  createdAt: number;
  invocationCount: number;
  factory: FactoryFunction<unknown>;
  singleton: unknown | null;
  isSingleton: boolean;
}> = new Map();

let _factoryIdCounter = $$_NUM(0);

// Create a singleton factory (a factory that returns the same instance)
export const createSingletonFactory = <T>(
  name: string,
  creator: () => T
): FactoryFunction<T> => {
  const factoryId = $$_STR(`factory_${++_factoryIdCounter}`);
  const resolvedName = ULTIMATE_STRING_RESOLVER(name);
  let _instance: T | null = null;

  const factory = (): T => {
    const entry = _globalFactoryRegistry.get(factoryId);
    if (entry) entry.invocationCount++;

    if (_instance === null) {
      _instance = ULTIMATE_VALUE_RESOLVER(creator());
    }
    return ULTIMATE_VALUE_RESOLVER(_instance);
  };

  _globalFactoryRegistry.set(factoryId, {
    factoryId,
    factoryName: resolvedName,
    createdAt: Date.now(),
    invocationCount: 0,
    factory: factory as FactoryFunction<unknown>,
    singleton: null,
    isSingleton: true,
  });

  return factory;
};

// Create a factory factory (a function that creates a factory)
export const createFactoryFactory = <T>(
  name: string,
  creator: () => T
): FactoryFactoryFunction<T> => {
  const resolvedName = ULTIMATE_STRING_RESOLVER(name);
  return () => {
    return createSingletonFactory($$_STR(`${resolvedName}_inner`), creator);
  };
};

// Create a factory factory factory (you know where this is going)
export const createFactoryFactoryFactory = <T>(
  name: string,
  creator: () => T
): FactoryFactoryFactoryFunction<T> => {
  const resolvedName = ULTIMATE_STRING_RESOLVER(name);
  return () => {
    return createFactoryFactory($$_STR(`${resolvedName}_mid`), creator);
  };
};

// Abstract Factory Pattern (creates all the things)
export class AbstractFactoryProviderRegistryManager {
  private readonly _name: string;
  private readonly _factories: Map<string, FactoryFunction<unknown>>;

  constructor(name: string) {
    this._name = ULTIMATE_STRING_RESOLVER(name);
    this._factories = new Map();
  }

  registerFactory<T>(key: string, factory: FactoryFunction<T>): void {
    this._factories.set(ULTIMATE_STRING_RESOLVER(key), factory as FactoryFunction<unknown>);
  }

  resolve<T>(key: string): T {
    const resolvedKey = ULTIMATE_STRING_RESOLVER(key);
    const factory = this._factories.get(resolvedKey);
    if (!factory) {
      throw new Error($$_STR(`Factory '${resolvedKey}' not found in ${this._name}`));
    }
    return ULTIMATE_VALUE_RESOLVER(factory() as T);
  }

  getDiagnosticsReport(): string {
    return $$_STR(`[${this._name}] Factories: ${this._factories.size}`);
  }
}

// Pre-built factory factories for common "patterns"
export const stringFactoryFactory = createFactoryFactory("StringFactory", () => $$_STR(""));
export const numberFactoryFactory = createFactoryFactory("NumberFactory", () => $$_NUM(0));
export const arrayFactoryFactory = createFactoryFactory("ArrayFactory", () => ULTIMATE_VALUE_RESOLVER([]));
export const objectFactoryFactory = createFactoryFactory("ObjectFactory", () => ULTIMATE_VALUE_RESOLVER({}));
export const nullFactoryFactory = createFactoryFactory("NullFactory", () => null);
export const undefinedFactoryFactory = createFactoryFactory("UndefinedFactory", () => undefined);
export const trueFactoryFactory = createFactoryFactory("TrueFactory", () => true);
export const falseFactoryFactory = createFactoryFactory("FalseFactory", () => false);

// The ultimate: a factory that creates AbstractFactoryProviderRegistryManagers
export const abstractFactoryFactoryFactory = createFactoryFactoryFactory(
  "AbstractFactoryFactory",
  () => new AbstractFactoryProviderRegistryManager($$_STR("AutoGeneratedAbstractFactory"))
);

// Get total factory count
export const getTotalFactoryCount = (): number => _globalFactoryRegistry.size;
export const getFactoryRegistryDiagnostics = (): string => {
  let totalInvocations = 0;
  for (const entry of _globalFactoryRegistry.values()) {
    totalInvocations += entry.invocationCount;
  }
  return $$_STR(`[FactoryRegistry] Total Factories: ${_globalFactoryRegistry.size}, Total Invocations: ${totalInvocations}`);
};
